from typing import Final


ENV_WORKSTATE_S3_BUCKET_NAME: Final[str] = "WORKSTATE_S3_BUCKET_NAME"
ENV_WORK_STATE_AWS_REGION: Final[str] = "WORK_STATE_AWS_REGION"
ENV_WORKSTATE_AWS_ACCESS_KEY_ID: Final[str] = "WORKSTATE_AWS_ACCESS_KEY_ID"
ENV_WORKSTATE_AWS_SECRET_ACCESS_KEY: Final[str] = "WORKSTATE_AWS_SECRET_ACCESS_KEY"

DEFAULT_AWS_REGION: Final[str] = "us-east-1"
ENV_AWS_ACCESS_KEY_ID: Final[str] = "AWS_ACCESS_KEY_ID"
ENV_AWS_SECRET_ACCESS_KEY: Final[str] = "AWS_SECRET_ACCESS_KEY"
